version: '3.0'

services:
  fruit-test-api:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: fruit-test-api
    image: 'fruit_test_api'
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - fruit_test_network

  fruit-test-db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: fruit-test-db
    restart: "no"
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - fruit-test-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fruit_test
      MYSQL_USER: fruit_test_admin
      MYSQL_PASSWORD: FRT1234
      MYSQL_ROOT_PASSWORD: FRT1234
    networks:
      - fruit_test_network

networks:
  fruit_test_network:
    driver: bridge

volumes:
  fruit-test-db:
    driver: local  